basePath: /
host: localhost:8080
info:
  contact: {}
  title: Cyberpunk 2077 hacking mini game
paths:
  /GetSequence:
    get:
      description: Get new matrix and sequences for hacking
      parameters:
      - description: id of Matrix
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: GetSequence
      tags:
      - Main tools
  /GetSequenceSugar:
    get:
      description: Get new matrix and sequences for hacking with human representation
      parameters:
      - description: id of Matrix
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: GetSequence For Human
      tags:
      - Additional methods
  /Hack:
    post:
      description: Try to hack matrix by your own
      parameters:
      - description: id of matrix
        in: query
        name: matrix_id
        required: true
        type: integer
      - description: path with clear coordinates to hack matrix
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Hack
      tags:
      - Main tools
swagger: "2.0"
