basePath: /
host: localhost:8081
info:
  contact: {}
  title: Utility to solve matrices of matrix_service
paths:
  /GetReports:
    get:
      description: Check reports of hacked matrixes
      produces:
      - application/json
      responses: {}
      summary: Reports
      tags:
      - Additional methods
  /HelpHack:
    post:
      description: Get ready answers how to hack matrixes of matrix_service
      parameters:
      - description: id of the matrix desired to be hacked
        in: query
        name: matrix_id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: HelpHack
      tags:
      - Main tools
swagger: "2.0"
